# CodeRabbit Configuration
# Optimized for AI review workflow

language: en-US

reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  # Ignore patterns
  path_filters:
    - "!**/*.lock"
    - "!**/package-lock.json"
    - "!**/yarn.lock"
    - "!**/*.min.js"
    - "!**/*.min.css"

  # Path-specific instructions
  path_instructions:
    - path: "skills/**/*.md"
      instructions: "Focus on clarity, completeness, and practical examples"
    - path: ".github/workflows/**"
      instructions: "Check for security implications and efficiency"
    - path: "global_workflows/**"
      instructions: "Verify pipeline consistency and persona alignment"

chat:
  auto_reply: true

# Review tools to enable
tools:
  # Linting (free)
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  shellcheck:
    enabled: true
